# 3.1. INTRODUCTION

## Import Numpy

In [1]:
# import numpy library
import numpy as np

## Checking Numpy Version

In [2]:
# checking numpy version
print(np.__version__)

1.25.2


In [3]:
# checking information of numpy
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for an array, function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPyth

# 3.2. ARRAY

## Making Array

In [4]:
array = np.array([1, 2, 3, 4, 5])

In [5]:
print(array)

[1 2 3 4 5]


In [6]:
print(type(array))

<class 'numpy.ndarray'>


In [7]:
# matemathics operation
A = [1, 2, 3, 4]
B = [5, 6, 7, 8]

arrayA = np.array(A)
arrayB = np.array(B)

In [8]:
arrayA + arrayB

array([ 6,  8, 10, 12])

In [9]:
arrayA * arrayB

array([ 5, 12, 21, 32])

In [10]:
# multiplication with scalar
arrayA * 10

array([10, 20, 30, 40])

## Array 0D

In [11]:
# just scalar
arr = np.array(99)

arr

array(99)

## Array 1D

In [12]:
# 1 dimension array
arr = np.array([1, 2, 3, 4, 5])

arr

array([1, 2, 3, 4, 5])

## Array 2D

In [13]:
# 2 dimensions array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

## Array 3D

In [14]:
# 3 dimensions array
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                 [[7, 8, 9], [10, 11, 12]]])

arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## Making 0s and 1s Array

In [15]:
# 1D
arr = np.zeros(5)

arr

array([0., 0., 0., 0., 0.])

In [16]:
# 2D
arr = np.zeros((5, 2))

arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
# 3D
arr = np.zeros((3, 4, 2))

arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
# 1s array
arr = np.ones((4, 2, 5))

arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

## Accessing Element in an Array

In [19]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
# access element of array
arr[1, 4]

10

In [21]:
arr[0:, 2::2]

array([[ 3,  5],
       [ 8, 10]])

In [22]:
arr[0:, 0::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

## Checking Data Type in an Array

In [23]:
arr = np.array([1, 2, 3, 4, 5])

arr

array([1, 2, 3, 4, 5])

In [24]:
arr.dtype

dtype('int32')

In [25]:
arr = np.array([1, 2, 3, 4,], dtype='S')

arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [26]:
arr = np.array([1, 2, 3, 4,], dtype='i')

arr

array([1, 2, 3, 4], dtype=int32)

## Changing Data Type in an Array

In [27]:
arr = np.array([1.3, 2.6, 5.1, 3.4, 4.5])

arr

array([1.3, 2.6, 5.1, 3.4, 4.5])

In [28]:
arr.dtype

dtype('float64')

In [29]:
arr = arr.astype('i')

arr

array([1, 2, 5, 3, 4], dtype=int32)

## Arange Function

In [30]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr = np.arange(10, 20, 2)

arr

array([10, 12, 14, 16, 18])

In [32]:
arr = np.arange(-1, 1, 0.1)

arr

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

# 3.3. SHAPE

## Shape of Array

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# checking dimension
arr.shape

(2, 3)

In [35]:
# checking total of element
arr.size

6

In [36]:
# checking dimension
arr.ndim

2

## Reshape 1D to 2D

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
arr.shape

(12,)

In [39]:
arr.ndim

1

In [40]:
arr = arr.reshape(6, 2)

arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [41]:
arr.ndim

2

## Reshape 1D to 3D

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
arr = arr.reshape(2, 3, 2)

arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [44]:
arr.ndim

3

## Using -1 to Reshape Array

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
arr = arr.reshape(3, 2, -1)

arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## Flattening in Array

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# flattening
arr = arr.reshape(-1)

arr

array([1, 2, 3, 4, 5, 6])

In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
# flattening
arr = arr.flatten()

arr

array([1, 2, 3, 4, 5, 6])

## Duplicate Array with copy()

In [51]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

In [52]:
arr[0] = 42

In [53]:
print(arr)

[42  2  3  4  5]


In [54]:
print(x)

[1 2 3 4 5]


## Duplicate Array with view()

In [55]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

In [56]:
arr[0] = 42

In [57]:
print(arr)

[42  2  3  4  5]


In [58]:
print(x)

[42  2  3  4  5]


# 3.4. OPERATION

## Iteration

In [59]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
for x in arr:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


## Iteration with nditer()

In [61]:
arr = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])

arr

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [63]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


## Iteration with ndenumerate()

In [64]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
for indeks, x in np.ndenumerate(arr):
    print(indeks, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10


## Join

In [67]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [69]:
arr1 = np.array([[1, 2], [6, 7]])
arr2 = np.array([[3, 4], [5, 8]])



In [71]:
arr = np.concatenate((arr1, arr2), axis=1)
arr

array([[1, 2, 3, 4],
       [6, 7, 5, 8]])

## Stack

In [72]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
arr.shape

(2, 3)

## Stack with hstack()

In [75]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

## Stack with vstack()

In [76]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

## Split

In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
arr = np.array_split(arr, 4)
arr

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]

In [80]:
arr = np.array_split(arr, 2)
arr

[array([[[1, 2]],
 
        [[3, 4]]]),
 array([[[5, 6]],
 
        [[7, 8]]])]

In [81]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10], 
                [11, 12, 13, 14, 15]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [83]:
arr = np.array_split(arr, 3, axis=1)
arr

[array([[[ 1,  2,  3,  4,  5]],
 
        [[ 6,  7,  8,  9, 10]],
 
        [[11, 12, 13, 14, 15]]]),
 array([], shape=(3, 0, 5), dtype=int32),
 array([], shape=(3, 0, 5), dtype=int32)]

## Search

In [87]:
arr = np.array([1, 8, 3, 4, 8, 6, 7, 8])
arr

array([1, 8, 3, 4, 8, 6, 7, 8])

In [88]:
x = np.where(arr == 8)
x

(array([1, 4, 7], dtype=int64),)

## Sort

In [89]:
arr = np.array([1, 3, 2, 5, 4, 6])
arr

array([1, 3, 2, 5, 4, 6])

In [90]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6])

# 3.5. FILTER

In [91]:
arr = np.array([100, 55, 89, 80, 70, 66, 30, 20, 45])
arr

array([100,  55,  89,  80,  70,  66,  30,  20,  45])

In [92]:
filter = arr[arr == 100]
filter

array([100])

In [95]:
filter =  arr[arr >= 50]
np.sort(filter)

array([ 55,  66,  70,  80,  89, 100])

In [96]:
arr = np.array([[1, 'one'], 
                [2, 'two'], 
                [3, 'three'], 
                [4, 'four']])
arr

array([['1', 'one'],
       ['2', 'two'],
       ['3', 'three'],
       ['4', 'four']], dtype='<U11')

In [97]:
filter = np.array(['two', 'four'])
filter

array(['two', 'four'], dtype='<U4')

In [98]:
arr_filtered = arr[np.in1d(arr[:, 1], filter)]
arr_filtered

array([['2', 'two'],
       ['4', 'four']], dtype='<U11')

# 3.6. RANDOM

In [99]:
from numpy import random

In [103]:
x = random.randint(100)
x

94

In [102]:
x = random.rand(100)
x

array([0.61108852, 0.03592814, 0.32422671, 0.44797791, 0.70744115,
       0.39393742, 0.42597892, 0.81330358, 0.90472461, 0.06263188,
       0.0474553 , 0.00299005, 0.45987514, 0.30795788, 0.20206617,
       0.71845815, 0.99521768, 0.47253054, 0.37967826, 0.00389879,
       0.06978068, 0.46204363, 0.10157623, 0.58743012, 0.03426743,
       0.87204531, 0.51962636, 0.54159581, 0.44987698, 0.0638722 ,
       0.08080401, 0.08356242, 0.01526355, 0.10920977, 0.25288466,
       0.28703611, 0.49578314, 0.84803475, 0.71065649, 0.92007727,
       0.14489503, 0.96151346, 0.72746188, 0.97308653, 0.90467336,
       0.02083215, 0.01798112, 0.47898538, 0.24269853, 0.27040694,
       0.26452819, 0.22024904, 0.32783732, 0.06114869, 0.5529683 ,
       0.31111056, 0.73710418, 0.62296918, 0.67933456, 0.06900361,
       0.61742361, 0.14638332, 0.58024035, 0.98894992, 0.12766575,
       0.35461502, 0.00325058, 0.88775664, 0.88597432, 0.26175668,
       0.59269415, 0.90590689, 0.65889357, 0.58070677, 0.82042

In [104]:
x = random.rand()
x

0.3723940196944302

In [105]:
arr =  random.randint(100, size=(3, 5))
arr

array([[11, 52, 21, 17, 98],
       [70, 43, 87, 44, 99],
       [42,  6, 51, 74, 56]])

In [109]:
arr =  random.rand(4, 2)
arr

array([[0.91449842, 0.75940206],
       [0.67996335, 0.44122138],
       [0.5157856 , 0.10712075],
       [0.87614956, 0.25077399]])

In [110]:
arr = random.choice([3, 5, 7, 9])
arr

9

In [112]:
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
arr

array([5, 4, 3, 1, 2])